sources:
  include:
    - ../../ElementX
    - ../../NSE
  exclude:
    - ../../ElementX/Sources/Mocks/SDK
templates:
  - AutoMockable.stencil
output:
  ../../ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
