name: Accessibility Tests

on:
  workflow_dispatch:

  schedule:
    - cron:  '0 2 * * 1-5'
    
jobs:
  tests:
    name: Tests
    runs-on: macos-26
    timeout-minutes: 150

    concurrency:
      # Only allow a single run of this workflow on each branch, automatically cancelling older runs.
      group: ${{ format('accessibility-tests-{0}', github.ref) }}
      cancel-in-progress: true

    steps:
      - uses: nschloe/action-cached-lfs-checkout@f46300cd8952454b9f0a21a3d133d4bd5684cfc2 #v1.2.3

      - name: Setup environment
        run: source ci_scripts/ci_common.sh && setup_github_actions_environment

      - name: Run tests
        run: swift run tools ci accessibility-tests

      - name: Archive artifacts
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: Results
          path: test_output/AccessibilityTests.xcresult.zip
          retention-days: 7
          if-no-files-found: ignore
